CREATE TABLE `tb_pedidos_gerais` (
  `DT_EMISSAO` datetime NOT NULL,
  `COD_CLIENTE` int NOT NULL,
  `VLR_TOTAL_PEDIDO` double NOT NULL,
  `NUM_PEDIDO` int NOT NULL,
  PRIMARY KEY (`NUM_PEDIDO`),
  KEY `FK_COD_CLIENTE_idx` (`COD_CLIENTE`),
  CONSTRAINT `FK_COD_CLIENTE` FOREIGN KEY (`COD_CLIENTE`) REFERENCES `tb_clientes` (`CODIGO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
