CREATE TABLE `tb_pedidos_produtos` (
  `COD_PEDIDO` int NOT NULL AUTO_INCREMENT,
  `COD_PRODUTO` int NOT NULL,
  `QTDE_PRODUTO` int NOT NULL,
  `VLR_TOTAL_PEDIDO` double NOT NULL,
  `NUM_PEDIDO` int NOT NULL,
  PRIMARY KEY (`COD_PEDIDO`),
  KEY `FK_COD_PRODUTO_idx` (`COD_PRODUTO`),
  CONSTRAINT `FK_COD_PRODUTO` FOREIGN KEY (`COD_PRODUTO`) REFERENCES `tb_produtos` (`COD_PRODUTO`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
